// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetAlbums(ctx context.Context) ([]Album, error)
	GetBooks(ctx context.Context) ([]Book, error)
}

var _ Querier = (*Queries)(nil)
